version: 2.0
jobs:
  build:
    docker:
      - image: finitereality/sourcelua
    steps:
      - checkout
      - run:
          name: Update git submodules
          command: git submodule sync && git submodule update --init
      - run:
          name: patch source SDK 2013
          command: pushd thirdparty/source-sdk-2013 && git apply ../../patches/source-sdk-2013.patch
      - run:
          name: build
          command: mkdir -p build && pushd build && cmake .. && make
